server:
  port: 8080

  servlet:
    session:
      cookie:
        http-only: true
  error:
    whitelabel:
      enabled: false

  compression:
    enabled: true
    mime-types:
      - application/json
      - application/xml
      - application/javascript
      - text/html
      - text/xml
      - text/plain
      - text/css
    min-response-size: 10240

spring:
  application:
    name: diploma-server

  jmx:
    enabled: false

  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/diploma_db
    username: postgres
    password: password
    # required by the option `hibernate.connection.provider_disables_autocommit: true`
    hikari:
      auto-commit: false

  data:
    jpa:
      repositories:
        bootstrap-mode: deferred

  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate.format_sql: true
      hibernate.id.new_generator_mappings: true
      hibernate.connection.autocommit: false
      hibernate.connection.provider_disables_autocommit: true
      hibernate.proc.param_null_passing: true
      hibernate.generate_statistics: false
      hibernate.jdbc.time_zone: UTC
      hibernate.jdbc.batch_versioned_data: true
      hibernate.jdbc.batch_size: 25
      hibernate.jdbc.fetch_size: 100
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true

  messages:
    basename: messages

  main:
    allow-bean-definition-overriding: true

  task:
    execution:
      thread-name-prefix: diploma-server-task-
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: diploma-server-scheduling-
      pool:
        size: 2

  output:
    ansi:
      console-available: true

security:
  jwt:
    secret: absolutelySecret
    expire: 900000
